import type { CollectionItem, CollectionSnapshot } from './types';

// Deterministic sample collection shown when the live database is not
// reachable. Clearly labeled as sample in the UI. Items are illustrative,
// modeled on the kinds of cards the business actually handles.

export const GAME_COLORS: Record<string, string> = {
  Pokémon: '#f0a03c',
  'One Piece': '#c92a2a',
  Other: '#5f6b7a',
};

const items: CollectionItem[] = [
  {
    id: 'c1',
    name: 'Carrot (Parallel)',
    setName: 'Two Legends',
    cardNumber: 'OP08-023',
    game: 'One Piece',
    kind: 'RAW',
    quantity: 4,
    gradeLabel: null,
    accentColor: GAME_COLORS['One Piece'],
  },
  {
    id: 'c2',
    name: 'Carrot (CS 25-26 Event Pack)',
    setName: 'Promotion Cards',
    cardNumber: 'P-070',
    game: 'One Piece',
    kind: 'RAW',
    quantity: 1,
    gradeLabel: null,
    accentColor: GAME_COLORS['One Piece'],
  },
  {
    id: 'c3',
    name: 'Shanks (Winner Pack 2026 Vol. 2)',
    setName: 'Promotion Cards',
    cardNumber: 'P-104',
    game: 'One Piece',
    kind: 'RAW',
    quantity: 1,
    gradeLabel: null,
    accentColor: GAME_COLORS['One Piece'],
  },
  {
    id: 'c4',
    name: 'Carrot',
    setName: "The Azure Sea's Seven",
    cardNumber: 'EB04-013',
    game: 'One Piece',
    kind: 'RAW',
    quantity: 2,
    gradeLabel: null,
    accentColor: GAME_COLORS['One Piece'],
  },
  {
    id: 'c5',
    name: 'Pikachu',
    setName: 'Celebrations',
    cardNumber: '005/025',
    game: 'Pokémon',
    kind: 'GRADED',
    quantity: 1,
    gradeLabel: 'PSA 10',
    accentColor: GAME_COLORS['Pokémon'],
  },
  {
    id: 'c6',
    name: 'Ditto Prism Star',
    setName: 'Lost Thunder',
    cardNumber: '154/214',
    game: 'Pokémon',
    kind: 'GRADED',
    quantity: 1,
    gradeLabel: 'PSA 10',
    accentColor: GAME_COLORS['Pokémon'],
  },
  {
    id: 'c7',
    name: 'Garchomp ex',
    setName: 'Paradox Rift',
    cardNumber: '245/182',
    game: 'Pokémon',
    kind: 'RAW',
    quantity: 3,
    gradeLabel: null,
    accentColor: GAME_COLORS['Pokémon'],
  },
  {
    id: 'c8',
    name: 'Evolving Skies Booster Box',
    setName: 'Sword & Shield',
    cardNumber: null,
    game: 'Pokémon',
    kind: 'SEALED',
    quantity: 2,
    gradeLabel: null,
    accentColor: GAME_COLORS['Pokémon'],
  },
  {
    id: 'c9',
    name: 'Brilliant Stars Booster Box',
    setName: 'Sword & Shield',
    cardNumber: null,
    game: 'Pokémon',
    kind: 'SEALED',
    quantity: 1,
    gradeLabel: null,
    accentColor: GAME_COLORS['Pokémon'],
  },
  {
    id: 'c10',
    name: 'OP-01 Romance Dawn Booster Box',
    setName: 'One Piece Card Game',
    cardNumber: null,
    game: 'One Piece',
    kind: 'SEALED',
    quantity: 1,
    gradeLabel: null,
    accentColor: GAME_COLORS['One Piece'],
  },
  {
    id: 'c11',
    name: 'O-Nami (Illustration)',
    setName: 'Awakening of the New Era',
    cardNumber: 'OP05-062',
    game: 'One Piece',
    kind: 'RAW',
    quantity: 2,
    gradeLabel: null,
    accentColor: GAME_COLORS['One Piece'],
  },
  {
    id: 'c12',
    name: 'Boa Hancock (Alt Art)',
    setName: 'Legacy of the Master',
    cardNumber: 'OP12-014',
    game: 'One Piece',
    kind: 'RAW',
    quantity: 1,
    gradeLabel: null,
    accentColor: GAME_COLORS['One Piece'],
  },
];

export const sampleCollection: CollectionSnapshot = {
  items,
  isLive: false,
};
